modLoader="javafml"
loaderVersion="[2,)"
license="MIT"
# issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="moresnifferflowers"
version="1.3.1"
displayName="More Sniffer Flowers"
# logoFile="moresnifferflowers.png"
authors="AbraXator, Nikdo53"
#displayTest="MATCH_VERSION"
description='''Lorem Ipsum'''
[[mixins]]
    config="more_sniffer_flowers.neoforge.mixins.json"
[[accesTransformers]]
    file="META-INF/accesstransformer.cfg"
[[dependencies.moresnifferflowers]]
    modId="neoforge"
    type="required"
    versionRange="[20.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moresnifferflowers]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,1.21)"
    ordering="NONE"
    side="BOTH"
