modLoader="javafml"
loaderVersion="[2,)"
license="MIT"
issueTrackerURL="https://github.com/AbraXator/MoreSnifferFlowers/issues"
[[mods]]
modId="moresnifferflowers"
version="${file.jarVersion}"
displayName="More Sniffer Flowers"
itemIcon="moresnifferflowers:dyespria"
logoFile="moresnifferflowers_logo.png"
authors="AbraXator, Nikdo53"
displayTest="MATCH_VERSION"
description='''Sniffer Flowers, but there's More of them and they actually do something'''
[[mixins]]
    config="more_sniffer_flowers.neoforge.mixins.json"
[[accesTransformers]]
    file="META-INF/accesstransformer.cfg"
[[dependencies.moresnifferflowers]]
    modId="neoforge"
    type="required"
    versionRange="[20.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moresnifferflowers]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"
