modLoader="javafml"
loaderVersion="[2,)"
license="MIT"
issueTrackerURL="https://github.com/AbraXator/MoreSnifferFlowers/issues"
[[mods]]
modId="moresnifferflowers"
version="${file.jarVersion}"
displayName="More Sniffer Flowers"
itemIcon="moresnifferflowers:dyespria"
logoFile="moresnifferflowers_logo.png"
authors="AbraXator, Nikdo53"
description="Minecraft mod expanding upon the sniffer, adding entire new mechanics, while keeping it somewhat vanilla friendly"
[[mixins]]
    config="more_sniffer_flowers.neoforge.mixins.json"
[[dependencies.moresnifferflowers]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.60-beta,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moresnifferflowers]]
    modId="minecraft"
    type="required"
    versionRange="[1.21, 1.21.1]"
    ordering="NONE"
    side="BOTH"
